import sys
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *

class mainUserUI(QWidget):
    def __init__(self):
        super().__init__()
        self.title = 'GIYA - Customers UI'
        self.x = 50
        self.y = 40
        self.width = 1270
        self.height = 680
        self.Icon = "appLogoico.png"
        self.setWindowTitle(self.title)
        self.setGeometry(self.x, self.y, self.width, self.height)
        self.setWindowIcon(QIcon(self.Icon))
        self.imagePath = ""

        #profile details
        self.name = "Ivan Norvy Guzman"
        self.email = "qinbguzman@tip.edu.ph"
        self.location = "Marikina City, Metro Manila, Philippines"
        self.username = "qinbguzman"
        self.bio = "“And suddenly you know: It's time to start something new and trust the magic of beginnings.” — Meister Eckhart"
        self.totalTours = 10
        self.favoriteLocation = "REGION IV"
        self.membershipTier = "bronzeTier.png"
        self.tier = "BRONZE TIER"

        self.initUI()
        self.menuBar() 
        self.dashboardPage()
        self.show()

    def initUI(self):
        self.backgroudTaskbar = QLabel(self)
        self.backgroudTaskbar.setStyleSheet("background-color:#494F5B;border: 0px 1px 0px 0px outset #666e7f")
        self.backgroudTaskbar.setGeometry(0,0,100,680)
        self.lineTaskbar1 = QLabel(self)
        self.lineTaskbar1.setStyleSheet("background-color:#2d3139")
        self.lineTaskbar1.setGeometry(0,60,100,2)
        self.backgroudLogo = QLabel(self)
        self.backgroudLogo.setStyleSheet("background-color:#d5d7dd")
        self.backgroudLogo.setGeometry(0,0,100,60)
        self.lineTaskbar = QLabel(self)
        self.lineTaskbar.setStyleSheet("background-color:#aaafbb")
        self.lineTaskbar.setGeometry(100,60,1280,2)
        self.backgroudBar = QLabel(self)
        self.backgroudBar.setStyleSheet("background-color:#f1f2f4;border: 1px outset #c6cad2")
        self.backgroudBar.setGeometry(100,0,1100,60)
        self.logo = QLabel(self)
        self.logo.resize(50,50)
        self.logo.move(22,5)
        self.pixmap = QPixmap(self.Icon)
        self.logo.setPixmap(QPixmap(self.pixmap))
        self.logo.setScaledContents(True)
        #Taskbar Buttons
        #Dashboard Page
        self.button1 = QPushButton("", self)
        self.button1.setIcon(QIcon("dashboardico.png"))
        self.button1.setToolTip("Go to your DASHBOARD.")
        self.button1.setIconSize(QSize(60,60))
        self.button1.setGeometry(14,90,70,70)
        self.button1.setStyleSheet("background-color:transparent")
        #self.button3.clicked.connect(self.dashboardPage)
        self.textbox1 = QLabel("DASHBOARD", self)
        self.textbox1.setStyleSheet("font-family:arial;font-weight:bold;color:#F5F5F5")
        self.textbox1.move(16,160)
        #About Us Page
        self.button2 = QPushButton("", self)
        self.button2.setIcon(QIcon("aboutUsico.png"))
        self.button2.setToolTip("Know About Us.")
        self.button2.setIconSize(QSize(45,45))
        self.button2.setGeometry(25,500,50,50)
        self.button2.setStyleSheet("background-color:transparent")
        #self.button4.clicked.connect(self.aboutUsPage)
        self.textbox2 = QLabel("ABOUT US", self)
        self.textbox2.setStyleSheet("font-family:arial;font-weight:bold;color:white")
        self.textbox2.move(22,560)
        #Profile
        self.button3 = QPushButton("", self)
        self.button3.setIcon(QIcon("profilePageico.png"))
        self.button3.setToolTip("Go to your Profile")
        self.button3.setIconSize(QSize(70,70))
        self.button3.setGeometry(10,195,80,80)
        self.button3.setStyleSheet("background-color:transparent")
        self.textbox3 = QLabel("PROFILE", self)
        self.textbox3.setStyleSheet("font-family:arial;font-weight:bold;color:white")
        self.textbox3.move(27,275)
        #History Events
        self.button4 = QPushButton("", self)
        self.button4.setIcon(QIcon("historyEvents.png"))
        self.button4.setToolTip("Go to your Profile")
        self.button4.setIconSize(QSize(50,50))
        self.button4.setGeometry(20,315,60,60)
        self.button4.setStyleSheet("background-color:transparent")
        self.textbox3 = QLabel("ACTIVITIES", self)
        self.textbox3.setStyleSheet("font-family:arial;font-weight:bold;color:white")
        self.textbox3.move(20,380)
        #Sign Out 
        self.button5 = QPushButton("SIGN OUT", self)
        self.button5.setIcon(QIcon("signOutico.png"))
        self.button5.setToolTip("Sign Out.")
        self.button5.setIconSize(QSize(30,30))
        self.button5.move(3,620)
        self.button5.resize(90,30)
        self.button5.setStyleSheet("background-color:transparent;color:white")
        #self.button5.clicked.connect(self.signOut)

    def menuBar(self):
        self.textDash = QLabel("Dashboard", self)
        self.textDash.move(130,15)
        self.textDash.setStyleSheet("font-family:century gothic;font-size:24px")
        self.taskBarButton = QPushButton("", self)
        self.taskBarButton.setIcon(QIcon("taskBar.png"))
        self.taskBarButton.setIconSize(QSize(30,30))
        self.taskBarButton.setGeometry(270,12,40,40)
        self.taskBarButton.setStyleSheet("background-color:transparent")
        self.buttonPic = QPushButton("", self)
        self.buttonPic.setIcon(QIcon("uploadImageico.ico"))
        self.buttonPic.setIconSize(QSize(70,50))
        self.buttonPic.setGeometry(1200,0,70,60)
        self.buttonPic.setStyleSheet("background-color:transparent")
        self.label = QLabel(self)
        self.label.setGeometry(1200,0,70,60)
        self.textboxUsername = QLabel(f"{self.username}", self)
        self.textboxUsername.move(1110,30)
        self.textboxUsername.setStyleSheet("font-family:arial;font-weight:bold;font-size:14px")
        self.textboxUsername1 = QLabel("Welcome to GIYA,", self)
        self.textboxUsername1.move(1110,10)

    def dashboardPage(self):
        #profile picture 
        self.buttonProfPic = QPushButton("", self)
        self.buttonProfPic.setIcon(QIcon("uploadImageico.ico"))
        self.buttonProfPic.setIconSize(QSize(130,130))
        self.buttonProfPic.resize(140,140)
        self.buttonProfPic.move(130,80)
        '''
        self.buttonUploadPic2 = QPushButton("Upload image", self)
        self.buttonUploadPic2.resize(120,25)
        self.buttonUploadPic2.move(140,200)
        self.buttonProfPic.clicked.connect(self.uploadProfilePic)
        self.buttonUploadPic2.clicked.connect(self.uploadProfilePic)
        '''
        self.label = QLabel(self)
        self.label.setGeometry(130,80,140,140)
        #profile details
        self.prfName = QLabel(f"{self.name}", self)
        self.prfName.resize(300,28)
        self.prfName.move(290,88)
        self.prfName.setStyleSheet("font-family:arial;font:bold;font-size:26px")
        self.prfEmail = QLabel(f"{self.email}", self)
        self.prfEmail.resize(300,17)
        self.prfEmail.move(290,118)
        self.prfEmail.setStyleSheet("font-family:arial;font-size:14px")
        self.prfLocation = QLabel(f"{self.location}", self)
        self.prfLocation.resize(300,17)
        self.prfLocation.move(290,143)
        self.prfLocation.setStyleSheet("font-family:arial;font-size:14px")
        self.prfBio = QLabel(f"{self.bio}", self)
        self.prfBio.setGeometry(290,150,380,80)
        self.prfBio.setStyleSheet("font-family:arial;font-size:14px;text-align")
        self.prfBio.setWordWrap(True)
        #recent Activities
        self.dashActivities = QLabel(self)
        self.dashActivities.setStyleSheet("background-color:#F8F8FF;border-style:outset;border-width:1px;border-color:#DCDCDC;border-radius:20px")
        self.dashActivities.setGeometry(120,250,550,200)
        self.lineDashAct = QLabel(self)
        self.lineDashAct.setStyleSheet("background-color:#aaafbb")
        self.lineDashAct.setGeometry(120,305,550,2)
        self.dashActIcon = QLabel(self)
        self.dashActIcon.setPixmap(QPixmap("upcomingActs.png"))
        self.dashActIcon.setGeometry(130,260,40,40)
        self.dashActIcon.setScaledContents(True)
        self.dashActText = QLabel("Upcoming Event", self)
        self.dashActText.move(180,268)
        self.dashActText.setStyleSheet("font-family:Arial;font-weight:bold;font-size:16px")

        self.dashActivities2 = QLabel(self)
        self.dashActivities2.setStyleSheet("background-color:#F8F8FF;border-style:outset;border-width:1px;border-color:#DCDCDC;border-radius:20px")
        self.dashActivities2.setGeometry(120,470,550,200)
        self.lineDashAct2 = QLabel(self)
        self.lineDashAct2.setStyleSheet("background-color:#aaafbb")
        self.lineDashAct2.setGeometry(120,525,550,2)
        self.dashActIcon2 = QLabel(self)
        self.dashActIcon2.setPixmap(QPixmap("tourGuide.png"))
        self.dashActIcon2.setGeometry(130,480,50,40)
        self.dashActIcon2.setScaledContents(True)
        self.dashActText2 = QLabel("Your Tourguide", self)
        self.dashActText2.move(185,490)
        self.dashActText2.setStyleSheet("font-family:Arial;font-weight:bold;font-size:16px")
        #festival of the Month
        self.dashFestival = QLabel(self)
        self.dashFestival.setStyleSheet("background-color:#F8F8FF;border-style:outset;border-width:1px;border-color:#DCDCDC;border-radius:20px")
        self.dashFestival.setGeometry(700,250,550,420)
        self.lineDashFest = QLabel(self)
        self.lineDashFest.setStyleSheet("background-color:#aaafbb")
        self.lineDashFest.setGeometry(700,305,550,2)
        self.dashFestIcon = QLabel(self)
        self.dashFestIcon.setPixmap(QPixmap("festivalMonth.png"))
        self.dashFestIcon.setGeometry(710,255,48,48)
        self.dashFestIcon.setScaledContents(True)
        self.dashFestText = QLabel("Festivals of the Month", self)
        self.dashFestText.move(765,270)
        self.dashFestText.setStyleSheet("font-family:Arial;font-weight:bold;font-size:16px")

        self.calendarTable = QTableWidget(self)
        self.calendarTable.setRowCount(10)
        self.calendarTable.setColumnCount(3)
        self.calendarTable.setColumnWidth(0,160)
        self.calendarTable.setColumnWidth(1,200)
        self.calendarTable.setColumnWidth(2,170)
        for i in range(10):
            self.calendarTable.setRowHeight(i,50)
        self.calendarTable.setItem(0,0, QTableWidgetItem("DATE/VENUE"))
        self.calendarTable.item(0,0).setTextAlignment(Qt.AlignCenter)
        self.calendarTable.setItem(0,1, QTableWidgetItem("FESTIVAL"))
        self.calendarTable.item(0,1).setTextAlignment(Qt.AlignCenter)
        self.calendarTable.setItem(0,2, QTableWidgetItem(""))
        self.calendarTable.setItem(1,0, QTableWidgetItem("March 10-12     Puerto Galera"))
        self.calendarTable.setItem(1,1, QTableWidgetItem("Malasimbo Festival"))
        self.calendarTable.setItem(2,0, QTableWidgetItem("March 21 - 27"))
        self.calendarTable.setItem(2,1, QTableWidgetItem("UNESCO-ITI World Theater Week"))
        self.calendarTable.setItem(3,0, QTableWidgetItem("First Week of March"))
        self.calendarTable.setItem(3,1, QTableWidgetItem("Island Garden City of Samal Festival"))
        self.calendarTable.setItem(4,0, QTableWidgetItem("March 8 Compostela Valley Province"))
        self.calendarTable.setItem(4,1, QTableWidgetItem("Anibina Bulawanun Festival"))
        self.calendarTable.setItem(5,0, QTableWidgetItem("March-April"))
        self.calendarTable.setItem(5,1, QTableWidgetItem("Holy Week"))
        self.calendarTable.setItem(6,0, QTableWidgetItem("Holy Week Marinduque"))
        self.calendarTable.setItem(6,1, QTableWidgetItem("Moriones Festival"))
        self.calendarTable.setItem(7,0, QTableWidgetItem("Holy Week General Luna, Quezon"))
        self.calendarTable.setItem(7,1, QTableWidgetItem("Centurion Festival"))
        self.calendarTable.setItem(8,0, QTableWidgetItem("Good Friday Jordan, Guimaras"))
        self.calendarTable.setItem(8,1, QTableWidgetItem("Ang Pagtaltal"))
        self.calendarTable.setItem(9,0, QTableWidgetItem("Good Friday Nueva Valencia"))
        self.calendarTable.setItem(9,1, QTableWidgetItem("Pangalap Ritual"))
        self.calendarTable.setItem(10,0, QTableWidgetItem("Holy Week Siquijor"))
        self.calendarTable.setItem(10,1, QTableWidgetItem("Witches Festival"))
        self.calendarTable.setGeometry(700,307,550,365)
        self.calendarTable.setStyleSheet("background-color:white;border-style:outset;border-width:1px;border-color:#DCDCDC;border-bottom-right-radius:20px;border-bottom-left-radius:20px;font-family:arial;font-size:16px")
        self.calendarTable.verticalHeader().setVisible(False)
        self.calendarTable.horizontalHeader().setVisible(False)
        self.calendarTable.setShowGrid(True)
        #statistics
        self.statBackground = QLabel(self)
        self.statBackground.setStyleSheet("background-color:#F8F8FF;border-style:outset;border-width:1px;border-color:#DCDCDC")
        self.statBackground.setGeometry(710,80,300,70)
        self.statToursIcon = QLabel(self)
        self.statToursIcon.setPixmap(QPixmap("numTours.png"))
        self.statToursIcon.setGeometry(710,80,70,70)
        self.statToursIcon.setScaledContents(True)
        self.statToursIcon.setStyleSheet("background-color:#1E90FF")
        self.statToursText = QLabel("TOURS", self)
        self.statToursText.setStyleSheet("font-family:Arial;font-weight:bold;font-size:16px;color:#808080")
        self.statToursText.move(860,125)
        self.statToursNum = QLabel(f"{self.totalTours}", self)
        self.statToursNum.setStyleSheet("font-family:Arial;font-weight:bold;font-size:28px")
        self.statToursNum.move(873,88)

        self.statBackground1 = QLabel(self)
        self.statBackground1.setStyleSheet("background-color:#F8F8FF;border-style:outset;border-width:1px;border-color:#DCDCDC")
        self.statBackground1.setGeometry(710,160,300,70)
        self.statFavLocIcon = QLabel(self)
        self.statFavLocIcon.setPixmap(QPixmap("favLoc.png"))
        self.statFavLocIcon.setGeometry(710,160,70,70)
        self.statFavLocIcon.setScaledContents(True)
        self.statFavLocIcon.setStyleSheet("background-color:#FCE043")
        self.statFavLocText = QLabel("FAVORITE LOCATION", self)
        self.statFavLocText.setStyleSheet("font-family:Arial;font-weight:bold;font-size:16px;color:#808080")
        self.statFavLocText.move(810,205)
        self.statFavLoc = QLabel(f"{self.favoriteLocation}", self)
        self.statFavLoc.setStyleSheet("font-family:Arial;font-weight:bold;font-size:28px")
        self.statFavLoc.move(820,168)

        self.statBackground2 = QLabel(self)
        self.statBackground2.setStyleSheet("background-color:#F8F8FF;border-style:outset;border-width:1px;border-color:#DCDCDC")
        self.statBackground2.setGeometry(1040,80,200,150)
        self.statTierImage = QLabel(self)
        self.statTierImage.setPixmap(QPixmap(self.membershipTier))
        self.statTierImage.setScaledContents(True)
        self.statTierImage.setGeometry(1090,105,100,100)
        self.statTierText = QLabel("MEMBERSHIP", self)
        self.statTierText.setStyleSheet("font-family:Arial;font-weight:bold;font-size:16px;color:#808080")
        self.statTierText.move(1085,85)
        self.statTierText2 = QLabel(f"{self.tier}", self)
        self.statTierText2.setStyleSheet("font-family:Arial;font-weight:bold;font-size:18px")
        self.statTierText2.move(1080,205)


    def uploadProfilePic(self):
        self.image = QFileDialog.getOpenFileName(self,'Open File','c\\','image file(*.jpg)')
        self.imagePath = self.image[0]
        self.pixmap = QPixmap(self.imagePath)
        self.label.setPixmap(QPixmap(self.pixmap))
        self.label.setScaledContents(True)
    


#executes the application
if __name__ == '__main__':
    app = QApplication(sys.argv)
    ui = mainUserUI()
    sys.exit(app.exec_())